### ISSUE TITLE
使用其他颜色来区分 README 中的 badge 是否会更好一些？

### ISSUE THREAD

**Issue by jerryshell** [wordshub/free-font#2]
比如：

「免费商用-无需授权」使用绿色

![](https://img.shields.io/badge/免费商用-无需授权-orange?style=flat-square&color=success)

```
https://img.shields.io/badge/免费商用-无需授权-orange?style=flat-square&color=success
```

「免费商用-需要授权」使用橙色

![](https://img.shields.io/badge/免费商用-需要授权-orange?style=flat-square)

```
https://img.shields.io/badge/免费商用-需要授权-orange?style=flat-square
```

**Comment by summerandwinter** [comment]
好主意，已经改了
