### ISSUE TITLE
诸繁体POSTER中 `长风几万里` 之 `里` 似乎简繁转换错误

### ISSUE THREAD

**Issue by Sinofine** [wordshub/free-font#3]
考虑到 `长风几万里` 中之 `里` 宜作 里程 之 里，则在简繁转换中应当保持 `里` 才对。
参见： https://zh.wikipedia.org/wiki/%E7%B0%A1%E7%B9%81%E8%BD%89%E6%8F%9B%E4%B8%80%E5%B0%8D%E5%A4%9A%E5%88%97%E8%A1%A8#cite_note-72

**Comment by ghost** [comment]
希望做成scoop仓库

**Comment by summerandwinter** [comment]
> 希望做成scoop仓库
