### ISSUE TITLE
关于破产字体

### ISSUE THREAD

**Issue by GuiyuOneiros** [wordshub/free-font#5]
fandol字体的授权可能存疑。虽然作者说法与CTAN上有矛盾的地方，不过还是建议备注一下。https://www.maoken.com/zhengyi/10.html

**Comment by summerandwinter** [comment]
确实存在争议，已去掉破产字体，感谢提醒

> fandol字体的授权可能存疑。虽然作者说法与CTAN上有矛盾的地方，不过还是建议备注一下。https://www.maoken.com/zhengyi/10.html

**Comment by UltimateAmitieKaiNiC** [comment]
还有这些：
https://www.maoken.com/zhengyi/746.html
https://www.maoken.com/zhengyi/171.html
https://www.maoken.com/zhengyi/1073.html
https://www.maoken.com/zhengyi/1062.html
https://www.maoken.com/zhengyi/1923.html
